-- this will find the system default pk
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE CONSTRAINT_NAME like 'PK%'
AND TABLE_NAME = 'dim_date' AND TABLE_SCHEMA = 'dbo'
--WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + CONSTRAINT_NAME), 'IsPrimaryKey') = 1
--AND TABLE_NAME = 'dim_date' AND TABLE_SCHEMA = 'dbo-SQL'

SELECT *
FROM [INFORMATION_SCHEMA].[KEY_COLUMN_USAGE]